export enum PATHNAME {
  MAIN = '/',
  FIND_DATA = '/finn-data',
  SEARCH = '/finn-data/sok',
  USE_DATA = '/finn-data/bruke-data',
  OFFER_DATA = '/tilby-data',
  HOW_TO_OFFER_DATA = '/tilby-data/hvordan-tilby-data',
  ABOUT = '/om-datafabrikken',
  NEWS = '/nyheter',
  COMMUNITY = '/datalandsbyen',
  COMMUNITY_POPULAR = '/datalandsbyen/populaer',
  COMMUNITY_RECENT = '/datalandsbyen/siste',
  COMMUNITY_TAGS = '/datalandsbyen/emneord',
  COMMUNITY_ABOUT = '/datalandsbyen/om-datalandsbyen',
  COMMUNITY_SEARCH = '/datalandsbyen/søk',
  DATA_SOURCES = '/datakilder',
  GUIDEANCE_AND_COMPETENCE = '/veiledere-og-kompetanse',
  PRIVATE_SECTOR = '/privat-sektor',
  CONTACT = '/kontakt',
  LEGAL_FRAMEWORK = '/juridiske-rammer-bruk-av-data',
  TEXT_FORMAT = '/tekst-format',
  DATASET_DETAILS = '/datasett',
  FDK_PUBLIC_SERVICES = '/public-services',
  FDK_DATA_SERVICES = '/dataservices',
  FDK_CONCEPTS = '/concepts',
  ORGANIZATION = '/virksomheter',
  METADATAQUALITY = '/metadatakvalitet',
  COURSES = '/kurs',
  GUIDANCE = '/veiledning',
  SITEMAP = '/nettstedkart',
  LEGAL_GUIDE = '/juridisk-veileder-for-datadeling'
}

export enum PARAGRAPH {
  BODY = 'paragraph--body',
  IMAGE = 'paragraph--image',
  VIDEO = 'paragraph--video',
  QUOTE = 'paragraph--quote',
  INFO_BOX = 'paragraph--law_text',
  MAIN_ELEMENT = 'paragraph--user_input_container'
}
