export const GET_COMMUNITY_CATEGORY_REQUESTED =
  'GET_COMMUNITY_CATEGORY_REQUESTED' as const;
export const GET_COMMUNITY_CATEGORY_SUCCEEDED =
  'GET_COMMUNITY_CATEGORY_SUCCEEDED' as const;
export const GET_COMMUNITY_CATEGORY_FAILED =
  'GET_COMMUNITY_CATEGORY_FAILED' as const;
export const RESET_COMMUNITY_CATEGORY = 'RESET_COMMUNITY_CATEGORY' as const;
