export const GET_COMMUNITY_CATEGORIES_REQUESTED =
  'GET_COMMUNITY_CATEGORIES_REQUESTED' as const;
export const GET_COMMUNITY_CATEGORIES_SUCCEEDED =
  'GET_COMMUNITY_CATEGORIES_SUCCEEDED' as const;
export const GET_COMMUNITY_CATEGORIES_FAILED =
  'GET_COMMUNITY_CATEGORIES_FAILED' as const;
export const RESET_COMMUNITY_CATEGORIES = 'RESET_COMMUNITY_CATEGORIES' as const;
