export const GET_DATA_SERVICES_RELATIONS_REQUESTED =
  'GET_DATA_SERVICES_RELATIONS_REQUESTED' as const;
export const GET_DATA_SERVICES_RELATIONS_SUCCEEDED =
  'GET_DATA_SERVICES_RELATIONS_SUCCEEDED' as const;
export const GET_DATA_SERVICES_RELATIONS_FAILED =
  'GET_DATA_SERVICES_RELATIONS_FAILED' as const;
export const RESET_DATA_SERVICES_RELATIONS =
  'RESET_DATA_SERVICES_RELATIONS' as const;
