export const GET_COMMUNITY_TAGS_REQUESTED =
  'GET_COMMUNITY_TAGS_REQUESTED' as const;
export const GET_COMMUNITY_TAGS_SUCCEEDED =
  'GET_COMMUNITY_TAGS_SUCCEEDED' as const;
export const GET_COMMUNITY_TAGS_FAILED = 'GET_COMMUNITY_TAGS_FAILED' as const;
export const RESET_COMMUNITY_TAGS = 'RESET_COMMUNITY_TAGS' as const;
