export const GET_COMMUNITY_TOPIC_REQUESTED =
  'GET_COMMUNITY_TOPIC_REQUESTED' as const;
export const GET_COMMUNITY_TOPIC_SUCCEEDED =
  'GET_COMMUNITY_TOPIC_SUCCEEDED' as const;
export const GET_COMMUNITY_TOPIC_FAILED = 'GET_COMMUNITY_TOPIC_FAILED' as const;
export const RESET_COMMUNITY_TOPIC = 'RESET_COMMUNITY_TOPIC' as const;
